### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Cupnfish** [rgripper/rusty-bomber#3]
- [x] Character movement step length
- [x] monster
- [x] bomb
- [x] Can eliminate walls
- [x] Increase props(e.g., speed up, increase bomb power

Thinking of these for the time being, we should be clear about what we want to do and avoid repetition. I can solve the step size problem first tonight.

**Comment by Cupnfish** [comment]
We need a new todos：

- [x] support wasm
- [x] replace new assets
- [x] optimizing the game flow
- [x] add more levels
- [ ] add audio effects

Or we could have bigger goals：

- [ ] Create a map editor
- [ ] Multiplayer support
- [ ] Support competitive mode and play against each other
- [ ] Support for mobile platforms
These are very difficult goals for now, but we can store them here and come back later when we get familiar with Bevy.

**Comment by rgripper** [comment]
I suggest we go through the first wave of goals, then post a link on Reddit to a web version.

For the second goal let's see a bit later

**Comment by Cupnfish** [comment]
699efcf49e7c0636899d099a1fb488678a9c96b6

**Comment by Cupnfish** [comment]
https://github.com/rgripper/game-temp-1/commit/27675b892c4d07197e2aa67497a4fe0d557f033d
replace new assets
